---
apiVersion: v1
kind: Service
metadata:
  name: coredns-omada
  namespace: coredns-omada
  labels:
    app: coredns-omada
  annotations:
spec:
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: dns-tcp
  - name: dns
    protocol: UDP
    port: 53
    targetPort: dns
  selector:
    app: coredns-omada
  type: LoadBalancer